### ISSUE TITLE
[Feature] 앨범 디테일뷰 상단UI 구성

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-DakeWill#5]
### Description
검색창의 앨범리스트 클릭시 넘어가게 되는 앨범의 디테일뷰 상단UI를 만듭니다.

### To-do
- [x] 앨범 Artwork 불러오기
- [x] 앨범 해당 아티스트 불러오기
- [x] 재생, 임의재생 버튼 구현

### etc
Collection에서 어떻게 값들을 가져올지 생각하면서 코딩을 하면 될 것 같다.

**Comment by sunshiningsoo** [comment]
[#9] 머지 완료!
